"""adds collection model

Revision ID: 20d3833c68b0
Revises: 1303b666b693
Create Date: 2025-11-07 14:47:56.534743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d3833c68b0'
down_revision = '1303b666b693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_table('collections_items',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collections_items_collection_id_collections')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_collections_items_item_id_items')),
    sa.PrimaryKeyConstraint('collection_id', 'item_id', name=op.f('pk_collections_items'))
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_items_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('collections_items')
    op.drop_table('collections')
    # ### end Alembic commands ###
